version: '3.8'

services:
  app:
    container_name: devin_app
    build:
      context: .
      dockerfile: Dockerfile.dev-prod-test-all
    environment:
      FLASK_ENV: development
    ports:
      - "5000:5000"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - .:/app
    networks:
      - devin_network

  db:
    container_name: devin_db
    image: postgres:latest
    environment:
      POSTGRES_DB: devin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - devin_network

  redis:
    container_name: devin_redis
    image: redis:latest
    networks:
      - devin_network

networks:
  devin_network:
    driver: bridge
