# Device Configuration for Devin Project

# General Device Settings
project_name: "Devin Project"
version: "1.0"

# PC Configuration
pc:
  - device_name: "DevinPC"
    os: "Windows"
    os_version: "10"
    hardware_specs:
      cpu: "Intel Core i7"
      ram: "16GB"
      storage: "512GB SSD"
      gpu: "NVIDIA GTX 1060"
    network_settings:
      ip_address: "192.168.1.10"
      subnet_mask: "255.255.255.0"
      gateway: "192.168.1.1"
    permissions:
      admin: true
      guest: false
    security:
      firewall_enabled: true
      antivirus: "Windows Defender"
      encryption: "AES-256"

# Mobile Configuration
mobile:
  - device_name: "DevinPhone"
    os: "Android"
    os_version: "11"
    hardware_specs:
      model: "Google Pixel 4a"
      ram: "6GB"
      storage: "128GB"
    network_settings:
      ip_address: "192.168.1.11"
      subnet_mask: "255.255.255.0"
      gateway: "192.168.1.1"
    permissions:
      root_access: false
    security:
      encryption: "AES-256"
      antivirus: "McAfee Mobile Security"
      two_factor_authentication: true

# IoT Device Configuration
iot_devices:
  - device_name: "DevinHub"
    type: "Smart Hub"
    model: "Hub v2.1"
    os: "Linux"
    os_version: "Ubuntu 20.04"
    network_settings:
      ip_address: "192.168.1.20"
      subnet_mask: "255.255.255.0"
      gateway: "192.168.1.1"
    security:
      encryption: "AES-128"
      firmware_version: "1.2.3"
    connected_devices:
      - "Smart Bulb"
      - "Smart Thermostat"
      - "Security Camera"

# Network Configuration
network:
  - device: "Router"
    model: "Netgear Nighthawk R7000"
    firmware_version: "V1.0.0.126_10.0.89"
    settings:
      wifi_band: "5GHz"
      ssid: "DevinNetwork"
      password: "SecurePassword123"
      mac_filtering: true
    qos:
      enabled: true
      max_bandwidth: "100Mbps"

# Cloud Storage Configuration
cloud_storage:
  - provider: "AWS S3"
    bucket_name: "devin-cloud-storage"
    region: "us-east-1"
    access_key: "YOUR_AWS_ACCESS_KEY"
    secret_key: "YOUR_AWS_SECRET_KEY"
    encryption: "AES-256"
    backup_schedule: "daily"
    retention_period: "30 days"

# IoT Device Security
iot_security:
  - device: "Smart Bulb"
    encryption: "AES-128"
    firewall_enabled: false
    two_factor_authentication: false
  - device: "Smart Thermostat"
    encryption: "AES-128"
    firewall_enabled: true
    two_factor_authentication: true
  - device: "Security Camera"
    encryption: "AES-256"
    firewall_enabled: true
    two_factor_authentication: true

# Testing Configuration
testing:
  - tool: "Wireshark"
    test_scenario: "Network Traffic Analysis"
  - tool: "ZAP (Zed Attack Proxy)"
    test_scenario: "IoT Device Vulnerability Testing"

# Logging Configuration
logging:
  level: "INFO"
  file: "/var/log/devin/device.log"
  enable_console_output: true
  rotate_logs: true
  retention_days: 7

# Additional Settings
debug_mode: false  # Set to true for detailed logging and verbose error reporting
maintenance_schedule: "weekly"  # Schedule for routine maintenance and updates

# API Connection Settings
api_connections:
  - service: "IoT Hub"
    api_key: "YOUR_IOT_HUB_API_KEY"
    endpoint: "https://api.iothub.com/connect"
    allowed_operations:
      - "monitor"
      - "control"
      - "update_firmware"

# Integration Configuration
integrations:
  - service: "Google Assistant"
    enabled: true
    webhook_url: "https://actions.google.com/smarthome"
  - service: "Amazon Alexa"
    enabled: true
    skill_id: "amzn1.ask.skill.YOUR_SKILL_ID"

# Security Configuration
encryption_method: "RSA-2048"
authentication_method: "OAuth2.0"
allowed_devices:
  - "PC"
  - "Mobile"
  - "IoT"

# Performance Optimization
optimization:
  enable_caching: true
  cache_size: "256MB"
  use_content_delivery_network: true
