# Robotics Configuration

# General Settings
robot_name: "DevinBot"
version: "1.0"
manufacturer: "Devin Industries"
communication_protocol: "Wi-Fi"  # Communication Protocol used for data transfer between the robot and control system

# Hardware Configuration
hardware:
  motors:
    type: "stepper"
    count: 4
    max_speed: "100 RPM"
    torque: "10 Nm"
    control_method: "PWM"  # Pulse Width Modulation
  sensors:
    - type: "Lidar"
      count: 2
      range: "10m"
      resolution: "2mm"
      interface: "I2C"
    - type: "ultrasonic"
      count: 4
      range: "5m"
      resolution: "1cm"
      interface: "GPIO"
    - type: "IMU"
      count: 1
      range: "±2000°/s"
      accuracy: "0.05%"
      interface: "UART"

# Power Management
power:
  battery_type: "Lithium-Ion"
  voltage: "14.8V"
  capacity: "5000mAh"
  power_consumption:
    active: "30W"
    idle: "5W"

# Software Configuration
software:
  os: "RTOS"  # Real-Time Operating System for deterministic behavior
  control_algorithm: "PID"  # Proportional-Integral-Derivative controller for stable motion
  communication_protocol: "MQTT"  # Messaging protocol for sensor data and control commands

# Network Configuration
network:
  ssid: "DevinBot_Network"
  password: "SecurePassword123"
  ip_address: "192.168.1.100"
  port: 1883

# Safety Features
safety:
  collision_avoidance:
    enabled: true
    methods: ["Lidar", "ultrasonic"]
  emergency_stop:
    enabled: true
    button_pin: 5

# Debugging & Monitoring
debugging:
  log_level: "DEBUG"
  log_file: "/var/log/devinbot/debug.log"
  enable_console_output: true
  monitor_metrics:
    - cpu_usage
    - memory_usage
    - battery_status

# Additional Settings
additional_settings:
  update_frequency: "1Hz"  # Frequency for sensor data updates
  idle_timeout: "10 minutes"  # Time before robot goes into sleep mode when idle

# Calibration Parameters
calibration:
  lidar:
    min_range: "0.2m"
    max_range: "10m"
    angle_offset: "0.5°"
  ultrasonic:
    min_range: "0.2m"
    max_range: "5m"
    angle_offset: "1°"
  imu:
    calibration_file: "/config/imu_calibration.yaml"
