# System-wide Settings Configuration for Devin Project

# General System Settings
general:
  system_name: "Devin AI Project" # Name of the system for identification
  environment: "production" # Environment type (development, staging, production)
  maintenance_mode: false # Maintenance mode flag
  uptime_monitoring: true # Enable monitoring of system uptime
  server_location: "USA" # Physical location of the server

# System Resources Management
resources:
  cpu_cores: 8 # Number of CPU cores allocated to the system
  memory_limit: "16GB" # Total memory allocated for the system
  disk_space: "500GB" # Total disk space available for the system
  swap_space: "8GB" # Swap space for handling memory spikes

# Security Settings
security:
  encryption: # Encryption settings for data at rest and in transit
    enabled: true
    protocols:
      - "TLS 1.2"
      - "TLS 1.3"
    data_encryption: "AES-256" # Use AES-256 for data encryption
  firewall:
    enabled: true # Enable the firewall
    rules:
      - action: "allow"
        protocol: "tcp"
        port: 80 # Allow HTTP traffic
      - action: "deny"
        protocol: "udp"
        port: 53 # Block DNS requests

# Logging and Monitoring
logging:
  enable_syslog: true # Forward logs to a centralized logging server
  log_level: "warn" # Set default log level to warn for system-wide logs
  retention_period: "60 days" # Keep logs for 60 days before rotating
  monitoring:
    enabled: true
    services:
      - service_name: "Zabbix"
        config:
          server: "https://zabbix.example.com"
          api_version: "5.0"
      - service_name: "Nagios"
        config:
          server: "https://nagios.example.com"
          api_key: "your_api_key_here"

# System Performance Optimization
performance_optimization:
  enable_disk_caching: true # Enable disk caching for faster read/write operations
  disk_cache_size: "10GB" # Set disk cache size to 10GB
  network_bandwidth: "100Mbps" # Set network bandwidth allocation
  load_balancing: true # Enable load balancing for high-traffic scenarios

# Backup and Restore
backup:
  enabled: true # Enable automated backups
  schedule: "weekly on Sundays at 3AM" # Backup schedule every week on Sunday at 3AM
  retention_period: "30 days" # Keep backups for 30 days
  storage:
    type: "S3"
    bucket_name: "devin-backups-system"

# System Integration
integrations:
  third_party_services:
    - service_name: "AWS Lambda"
      integration_type: "serverless"
      functions:
        - name: "data_processing"
        - name: "image_analysis"
    - service_name: "Google Cloud"
      integration_type: "API"
      services:
        - "Cloud AI"
        - "Pub/Sub"
    - service_name: "Microsoft Azure"
      integration_type: "cloud services"
      services:
        - "Azure Machine Learning"
        - "Azure Functions"

# Network Configuration
network:
  enable_private_networking: true # Enable private network for internal services
  external_ip: "192.168.1.100" # Set public IP for external access
  vpn_support:
    enabled: true
    configuration_file: "/etc/vpn/config.ovpn"

# System Health and Diagnostics
health_checks:
  enabled: true # Enable regular health checks
  interval: "5 minutes" # Check system health every 5 minutes
  alert_threshold:
    cpu_usage: 85 # Trigger alert if CPU usage exceeds 85%
    memory_usage: 80 # Trigger alert if memory usage exceeds 80%
    disk_usage: 90 # Trigger alert if disk usage exceeds 90%

# Notes:
# - Modify settings as needed for your environment.
# - Sensitive information should be managed securely.
# - Consult with an IT professional for detailed implementation.
