# User-Specific Preferences Configuration for Devin Project

# User Preferences Configuration
user_preferences:
  theme: "dark" # User's preferred theme (light, dark, custom)
  language: "en" # Preferred language for the user interface
  notification_settings:
    email: true # Enable email notifications
    sms: false # Disable SMS notifications
    push: true # Enable push notifications
  privacy_settings:
    profile_visibility: "friends_only" # Profile visibility setting (public, friends_only, private)
    ad_preferences:
      personalized_ads: false # Disable personalized ads
      show_ads_from: "selected_brands" # Show ads from selected brands or none
  time_format: "24-hour" # User's preferred time format (24-hour, 12-hour)
  date_format: "YYYY-MM-DD" # User's preferred date format
  timezone: "UTC" # User's preferred timezone
  accessibility:
    high_contrast: false # Enable high contrast mode
    text_to_speech: true # Enable text-to-speech for reading content
    screen_reader: false # Enable screen reader
  analytics:
    enabled: true # Enable analytics tracking for user preferences
    last_updated: "2024-12-20T12:00:00Z" # Timestamp of the last preferences update
  customizations:
    homepage_layout: "grid" # Preferred homepage layout (grid, list, compact)
    font_size: "medium" # Preferred font size (small, medium, large)
    widget_preferences:
      - "weather"
      - "calendar"
      - "news" # List of user's preferred widgets for the dashboard

# Note:
# - Sensitive user preferences should be handled securely.
# - Customizable settings should be user-friendly and accessible.
# - Consult with a professional for detailed implementation.
