# Windows-Specific Configurations for Devin Project

# Operating System Specific Configurations
windows:
  package_manager: "winget" # Default package manager for Windows (Windows Package Manager)
  preferred_shell: "C:\\Windows\\System32\\cmd.exe" # Preferred shell for execution
  firewall:
    enabled: true # Enable the Windows Firewall
    rules:
      - "IN allow all" # Allow all incoming connections
      - "OUT allow all" # Allow all outgoing connections
      - "IN allow localhost" # Allow local loopback
      - "OUT deny all" # Block all external outgoing connections by default
  service_management:
    enabled: true # Use Windows Services for management
    default_runlevel: "Automatic" # Default startup type for services
  network:
    settings:
      hostname: "devin-windows" # Default hostname for the system
      static_ip:
        enabled: false # Disable static IP configuration (usually not recommended for Windows)
        address: "" # No static IP by default
        netmask: "" # No netmask by default
        gateway: "" # No gateway by default
      dns_servers:
        - "8.8.8.8" # Google DNS
        - "8.8.4.4" # Alternative Google DNS
  directory_structure:
    home_dir: "C:\\Users\\devin" # Home directory for the Devin project
    data_storage: "C:\\ProgramData\\devin\\data" # Directory for storing data
    log_dir: "C:\\ProgramData\\devin\\logs" # Directory for log files
    config_dir: "C:\\ProgramData\\devin" # Directory for configuration files
  scheduled_tasks:
    enabled: true # Enable scheduled tasks for regular tasks
    tasks:
      - name: "Backup Script"
        schedule: "Weekly" # Weekly backup
        trigger: "At 2 AM on Sunday"
        command: "C:\\devin\\scripts\\backup.bat"
      - name: "Clean Temporary Files"
        schedule: "Daily" # Daily cleanup
        trigger: "At 3 AM every day"
        command: "C:\\devin\\scripts\\cleanup.bat"
  system_updates:
    enabled: true # Enable automatic system updates
    update_frequency: "daily" # Frequency of updates (hourly, daily, weekly)
  file_permissions:
    user: "devin" # User for Devin application
    group: "devin" # Group for Devin application
    permissions: "755" # Default directory permissions
  last_updated: "2024-12-20T12:00:00Z" # Timestamp of the last Windows-specific configuration update

# Note:
# - Adjust the scheduled task commands (`backup.bat` and `cleanup.bat`) according to your scripts.
# - Modify the network settings if your use case requires a specific setup.
# - Update the directories and paths according to your project’s directory structure.
